CREATE TABLE owner
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id VARCHAR(255)                            NOT NULL,
    owner_type  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_owner PRIMARY KEY (id)
);

CREATE TABLE account
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number        VARCHAR(20)                             NOT NULL,
    owner_id      BIGINT                                  NOT NULL,
    type          VARCHAR(255)                            NOT NULL,
    currency      VARCHAR(255)                            NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    created_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    modified_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    closed_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    version       INTEGER                                 NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

CREATE INDEX index_number ON account (number);

ALTER TABLE account
    ADD CONSTRAINT FK_ACCOUNT_ON_OWNER FOREIGN KEY (owner_id) REFERENCES owner (id);
