CREATE TABLE account_number_sequence
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_type  SMALLINT                                NOT NULL,
    current_count BIGINT                                  NOT NULL,
    version       BIGINT,
    CONSTRAINT pk_account_number_sequence PRIMARY KEY (id)
);

CREATE TABLE free_account_numbers
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_type   SMALLINT                                NOT NULL,
    account_number VARCHAR(20)                             NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_free_account_numbers PRIMARY KEY (id)
);